'use client'
import {useEffect,useState} from 'react'
import {v4 as uuid} from 'uuid'
import Link from 'next/link'
import {ArrowLeft,CheckCircle2,Clock3,ReceiptText,ShieldCheck,RefreshCw} from 'lucide-react'
import {RefundData,RefundRecord,STATUS,CUSTOMER_STATUS,WON} from './types'
import './refunds.css'

export default function RefundCenter({admin=false}:{admin?:boolean}) {
 const [data,setData]=useState<RefundData|null>(null),[error,setError]=useState(''),[loadError,setLoadError]=useState(''),[busy,setBusy]=useState(false)
 const [requestKey,setRequestKey]=useState('')
 const [order,setOrder]=useState(''),[kind,setKind]=useState('unused'),[reason,setReason]=useState(''),[job,setJob]=useState('')
 const [quote,setQuote]=useState<{eligible:boolean;amount:number;coins:number;paid:number;available:number;jobStatus:string|null;message:string;matches?:{transactionKey:string;amount:number}[]}|null>(null)
 const [notice,setNotice]=useState(''),[filter,setFilter]=useState('needs'),[selected,setSelected]=useState<RefundRecord|null>(null),[note,setNote]=useState('')
 const endpoint=admin?'/api/admin/refunds':'/api/refunds'
 async function load(){try{const r=await fetch(endpoint,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'내역을 불러오지 못했어요.');setData(d);setLoadError('')}catch(e){setLoadError(e instanceof Error?e.message:'연결을 확인해주세요.')}}
 useEffect(()=>{load()},[admin])
 useEffect(()=>{if(notice){const el=document.getElementById('refund-feedback');el?.scrollIntoView({behavior:'auto',block:'center'});el?.focus({preventScroll:true})}},[notice])
 useEffect(()=>{if(order||selected)document.getElementById('refund-form')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})},[order,selected])
 async function review(r:RefundRecord){setBusy(true);setError('');setSelected(r);setNote('');setQuote(null);try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'quote',id:r.id})});const q=await res.json();if(!res.ok)throw Error(q.error);setQuote(q)}catch(e){setError(e instanceof Error?e.message:'기록을 확인하지 못했습니다.')}finally{setBusy(false)}}
 useEffect(()=>{if(!data?.refunds.some(r=>['queued','processing','uncertain'].includes(r.status)))return;const t=setInterval(load,7000);return()=>clearInterval(t)},[data,admin])
 async function send(body:Record<string,unknown>){setBusy(true);setNotice('');setError('');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'요청하지 못했어요.');setNotice(d.message||'요청을 접수했어요. 처리 내역에서 상태를 확인해주세요.');setSelected(null);setOrder('');setReason('');setNote('');await load()}catch(e){setError(e instanceof Error?e.message:'요청을 확인해주세요.')}finally{setBusy(false)}}
 const chosen=data?.orders.find(o=>o.order_id===order)
 const estimate=chosen?.tracked&&kind==='unused'?Math.min(chosen.amount-chosen.refunded_amount,Math.ceil(chosen.amount*chosen.available/Math.max(1,chosen.coins))):null
 const needs=(data?.refunds??[]).filter(r=>['review','blocked','uncertain'].includes(r.status)).sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at))
 const list=admin&&filter==='needs'?needs:data?.refunds??[]
 function openOrder(id:string){setError('');setRequestKey(uuid());setOrder(id);setKind('unused');setReason('');setJob('');setNotice('')}
 return <main className={'refund-center '+(admin?'refund-admin':'')}>
  <header className="refund-header"><Link href={admin?'/payments':'/storage'} aria-label="돌아가기"><ArrowLeft size={22}/></Link><span>사주궁 <small>{admin?'주인장 관리':'내 이용 내역'}</small></span><button aria-label="내역 새로고침" onClick={load} disabled={busy}><RefreshCw size={19}/></button></header>
  <section className="refund-title"><p>{admin?'결제와 이용 기록을 함께 확인하세요':'결제부터 환불까지, 한곳에서'}</p><h1>{admin?'환불 검토함':'결제 · 환불 내역'}</h1></section>
  {loadError&&<div className="refund-alert" role="alert">{loadError}<button onClick={load}>다시 확인</button>{!data&&<Link href="/login">로그인하기</Link>}</div>}
  {notice&&<div id="refund-feedback" tabIndex={-1} className="refund-notice" role="status"><CheckCircle2 size={18}/>{notice}</div>}
  {error&&!chosen&&!selected&&<div className="refund-alert" role="alert">{error}</div>}
  {!data&&!loadError&&<p role="status">내역을 불러오고 있어요…</p>}
  {data&&<>
   {admin?<><div className="refund-metrics"><div><span>확인할 요청</span><strong>{needs.length}<small>건</small></strong></div><div><span>취소 완료</span><strong>{data.refunds.filter(r=>r.status==='succeeded').length}<small>건</small></strong></div></div><div className="refund-note"><ShieldCheck size={20}/><p>조건이 확인된 미사용 환불은 자동 처리됩니다.<br/>여기서는 예외 사유와 처리 결과를 확인하세요.</p></div><div className="refund-tabs" role="group" aria-label="환불 목록 필터"><button aria-pressed={filter==='needs'} onClick={()=>setFilter('needs')}>확인 필요 {needs.length}</button><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>전체 내역 {data.refunds.length}</button></div></>:<>
    <div className="refund-note"><ShieldCheck size={21}/><p>자동 환불 조건에 맞는 미사용 유료 엽전은 기록 확인 후 처리해요. 그 밖의 요청은 담당자가 검토해요.</p></div>
    <h2>내 결제</h2>{data.orders.length===0&&<div className="refund-empty"><ReceiptText/><p>아직 결제 내역이 없어요.</p></div>}
    {data.orders.map(o=><article className="refund-order" key={o.order_id}><div className="refund-row"><strong>{o.product==='unlock'?'전체 해석 이용권':`엽전 ${o.coins}냥`}</strong><b>{WON(o.amount)}</b></div><p className="refund-date">{new Date(o.created_at).toLocaleDateString('ko-KR')} · 주문 {o.order_id.slice(-8)}</p><div className="refund-row refund-balance"><span>{o.tracked?`미사용 유료 엽전 ${o.available}냥`:'구매·사용 내역 확인 필요'}</span>{o.refunded_amount>0&&<span>취소 {WON(o.refunded_amount)}</span>}</div><button className="refund-secondary" onClick={()=>openOrder(o.order_id)}>환불 가능 내역 확인</button></article>)}
    <h2>처리 내역</h2>
   </>}
   {!list.length&&<div className="refund-empty"><CheckCircle2/><p>{admin?'지금 확인할 요청이 없어요.':'아직 환불 요청이 없어요.'}</p></div>}
   {list.map(r=><article className="refund-record" key={r.id}><div className="refund-row"><span className={'refund-status '+r.status}>{(admin?STATUS:CUSTOMER_STATUS)[r.status]}</span><b>{r.amount>0?WON(r.amount):'금액 확인 예정'}</b></div><p>{r.reason||'미사용 유료 엽전 환불'}</p><p className="refund-date">주문 {r.order_id.slice(-8)} · {new Date(r.created_at).toLocaleString('ko-KR')}</p>{admin&&['review','blocked','uncertain'].includes(r.status)&&<p className="refund-context">접수 후 {Math.max(0,Math.floor((Date.now()-Date.parse(r.created_at))/3600000))}시간{Date.now()-Date.parse(r.created_at)>86400000?' · 우선 확인해주세요.':''}</p>}{r.review_reason&&<p className="refund-context">{r.review_reason}</p>}{r.decision_note&&<p className="refund-context">답변: {r.decision_note}</p>}{['queued','processing','uncertain'].includes(r.status)&&<p className="refund-context"><Clock3 size={15}/> 취소 결과를 확인하고 있어요. 같은 요청을 다시 보내지 않아도 됩니다.</p>}{r.status==='succeeded'&&<p className="refund-context">결제 취소가 확인됐어요. 카드·은행 반영까지는 시간이 더 걸릴 수 있어요.</p>}{admin&&['review','blocked','uncertain'].includes(r.status)&&<button className="refund-primary" disabled={busy} onClick={()=>review(r)}>기록 확인 · 결정하기</button>}{admin&&['blocked','uncertain','queued','processing'].includes(r.status)&&<button className="refund-secondary" disabled={busy} onClick={()=>send({action:'reconcile',id:r.id})}>결제 상태 다시 확인</button>}</article>)}
  </>}
  {chosen&&<section id="refund-form" className="refund-form" aria-label="환불 요청"><div className="refund-row"><h2>환불 요청</h2><button className="refund-text" onClick={()=>setOrder('')}>닫기</button></div><p>주문 {chosen.order_id.slice(-8)}</p><label>요청 유형<select value={kind} onChange={e=>{setKind(e.target.value);setRequestKey(uuid())}}><option value="unused">미사용 유료 엽전</option><option value="failure">생성 실패 · 결과 미제공</option><option value="content">해석 내용 · 제공 항목 문제</option><option value="duplicate">중복 결제가 의심돼요</option></select></label>{kind!=='unused'&&<label>관련 해석<select value={job} onChange={e=>{setJob(e.target.value);setRequestKey(uuid())}}><option value="">선택하지 않음</option>{chosen.jobs.map(j=><option key={j.id} value={j.id}>{j.product} · {j.status==='done'?'제공 완료':j.status==='failed'?'생성 실패':j.status}</option>)}</select></label>}<label>요청 내용 {kind==='unused'?'(선택)':'(필수)'}<textarea maxLength={600} value={reason} onChange={e=>setReason(e.target.value)} placeholder={kind==='unused'?'남기실 내용이 있으면 적어주세요.':'어떤 문제가 있었는지 알려주세요.'}/></label><div className="refund-estimate"><span>예상 환불액</span><strong>{estimate!==null?WON(estimate):'기록 확인 후 안내'}</strong></div><p className="refund-context">최종 금액은 신청 시점의 사용 기록으로 확인합니다. 처리 중인 엽전은 사용할 수 없으며, 최초 무료 이용 횟수는 초기화되지 않아요.</p>{error&&<div className="refund-alert" role="alert">{error}</div>}<button disabled={busy||(kind!=='unused'&&!reason.trim())} className="refund-primary" onClick={()=>send({orderId:order,kind,reason,jobId:job||null,requestId:requestKey})}>{busy?'요청 확인 중…':'환불 요청하기'}</button></section>}
  {selected&&<section id="refund-form" className="refund-form" aria-label="관리자 환불 결정"><div className="refund-row"><h2>요청 검토</h2><button className="refund-text" onClick={()=>setSelected(null)}>닫기</button></div><p>주문 {selected.order_id}</p><p>{selected.reason}</p><p>{selected.review_reason}</p><p className="refund-context">구매·사용 내역과 요청 사유를 확인한 뒤 결정해주세요.</p>{quote?<div className="refund-quote"><p>실제 결제 {WON(quote.paid??0)} · 미사용 {quote.available}냥</p><p>해석 상태: {quote.jobStatus==='done'?'제공 완료':quote.jobStatus==='failed'?'생성 실패':'해당 없음'}</p><div className="refund-estimate"><span>승인 시 환불액</span><strong>{WON(quote.amount)}</strong></div><p>{quote.message}</p></div>:<p role="status">결제·사용 기록을 확인하고 있어요…</p>}<label>고객에게 안내할 처리 사유<textarea maxLength={600} value={note} onChange={e=>setNote(e.target.value)} placeholder="확인한 내용과 처리 사유를 적어주세요."/></label>{error&&<div className="refund-alert" role="alert">{error}</div>}<div className="refund-actions">{quote?.matches?.map(m=><button className="refund-primary" disabled={busy||!note.trim()} key={m.transactionKey} onClick={()=>send({action:'external',id:selected.id,note,transactionKey:m.transactionKey})}>토스 취소 {WON(m.amount)} 확인 · 반영 ({m.transactionKey.slice(-6)})</button>)}<button className="refund-primary" disabled={busy||!note.trim()||!quote?.eligible} onClick={()=>send({action:'approve',id:selected.id,note,expectedAmount:quote?.amount})}>환불 승인</button><button className="refund-secondary" disabled={busy||!note.trim()||selected.status!=='review'} onClick={()=>send({action:'reject',id:selected.id,note})}>사유를 안내하고 종료</button></div></section>}
  <footer className="refund-footer"><Link href="/terms#refund">이용약관 · 환불 기준</Link><a href="mailto:sajuya.help@gmail.com">고객센터에 문의</a></footer>
 </main>
}
