import {PGlite} from '@electric-sql/pglite'
import {readFileSync} from 'node:fs'
import assert from 'node:assert/strict'
const db=new PGlite()
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;CREATE SCHEMA auth;CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT NULL::uuid $$;`)
for(const p of ['supabase-schema.sql','supabase-schema-upgrade.sql','supabase-schema-upgrade-3-daily.sql','supabase-launch-security.sql'])await db.exec(readFileSync(p,'utf8'))
await db.exec("INSERT INTO users(id,yeobjeun_balance) VALUES('legacy',3)")
await db.exec(readFileSync('supabase-refunds.sql','utf8'))
const value=async(sql,args=[])=>(await db.query(sql,args)).rows[0]?.value
const order=async(id,user,product='three')=>{await db.query("INSERT INTO users(id,yeobjeun_balance) VALUES($1,0) ON CONFLICT DO NOTHING",[user]);await db.query("INSERT INTO commerce_orders(order_id,user_id,product,amount,coins,consent_version,payment_key) VALUES($1,$2,$3,$4,$5,'test',$6)",[id,user,product,product==='one'?1900:4900,product==='one'?1:3,'key-'+id]);return value('SELECT complete_payment($1,$2,$3) value',[id,'key-'+id,product==='one'?1900:4900])}
const reserve=(u,key,product='saju')=>value('SELECT reserve_generation($1,$2,$3,$2,$4) value',[u,key,product,{name:'테스트'}])
const finish=(j,success)=>value('SELECT finish_generation($1,$2,$3,$4,$5,$6) value',[j.id,j.attempt,success,success?'wire':null,success?{titles:[]}:null,{}])
const request=(u,o,key,kind='unused',job=null)=>value('SELECT request_refund($1,$2,$3,$4,$5,$6) value',[u,o,kind,'테스트 요청',key,job])
const settle=(r,tx='tx-'+r.id)=>value('SELECT settle_refund($1,$2,$3) value',[r.id,tx,r.amount])
const balance=u=>value('SELECT yeobjeun_balance value FROM users WHERE id=$1',[u])
await order('o1','buyer')
await value("SELECT complete_payment('o1','key-o1',4900) value")
assert.equal(await balance('buyer'),3)
// Migration re-run must NOT duplicate newly-created wallets.
await db.exec(readFileSync('supabase-refunds.sql','utf8'))
assert.equal(await value("SELECT sum(available)::int value FROM credit_lots WHERE user_id='buyer'"),3)
const j=await reserve('buyer','first');await finish(j,true)
const r=await request('buyer','o1','req1')
assert.equal(r.status,'queued');assert.equal(r.coins,2);assert.equal(r.amount,3267);assert.equal(await balance('buyer'),0)
assert.equal((await reserve('buyer','during-refund')).error,'balance')
const duplicate=await Promise.all(Array.from({length:10},(_,i)=>request('buyer','o1','repeat'+i)))
assert.ok(duplicate.every(x=>x.id===r.id))
assert.equal((await request('legacy','o1','foreign')).error,'missing')
assert.ok(await value('SELECT claim_refund($1) value',[r.id]));assert.equal(await value('SELECT claim_refund($1) value',[r.id]),null)
await assert.rejects(()=>value('SELECT settle_refund($1,$2,$3) value',[r.id,'tamper',4900]))
await settle(r);await settle(r)
assert.equal(await value("SELECT refunded_amount value FROM commerce_orders WHERE order_id='o1'"),3267)
assert.equal((await reserve('buyer','first')).cached,true)
// Remaining used content requires a human decision; max total refund cannot exceed purchase.
const content=await request('buyer','o1','issue','content',j.id)
assert.equal(content.status,'review')
const approved=await value('SELECT decide_refund($1,$2,true,$3,1633) value',[content.id,'owner','누락된 항목 확인'])
assert.equal(approved.amount,1633)
await settle(approved)
assert.equal(await value("SELECT refunded_amount value FROM commerce_orders WHERE order_id='o1'"),4900)
assert.equal((await reserve('buyer','first')).error,'refunded')
assert.equal(await value('SELECT access_verified value FROM readings WHERE id=(SELECT reading_id FROM generation_jobs WHERE id=$1)',[j.id]),false)
// Failed generation returns the SAME lot once and can be refunded without affecting trial rights.
await order('o2','failure','one');const f=await reserve('failure','fail');await finish(f,false);await finish(f,false)
assert.equal(await balance('failure'),1)
const fr=await request('failure','o2','fail-refund','failure',f.id);assert.equal(fr.status,'queued');assert.equal(fr.amount,1900);await settle(fr)
const trial=await reserve('failure','daily','daily');await finish(trial,true)
assert.equal((await reserve('failure','daily-next','daily')).error,'trial_used')
// Free credits are consumed before paid credits. Both currencies stay attributable.
await order('o3','free-first','one')
await db.exec("UPDATE users SET streak_days=6,last_visit=(now() AT TIME ZONE 'Asia/Seoul')::date-1 WHERE id='free-first'")
await value("SELECT check_attendance('free-first') value")
const freeJob=await reserve('free-first','gift');await finish(freeJob,true)
assert.equal(await value("SELECT available value FROM credit_lots WHERE order_id='o3'"),1)
assert.equal((await request('free-first','o3','cash')).amount,1900)
// Unknown historical sources and external cancellations never receive blind auto-refunds.
await db.exec("INSERT INTO commerce_orders(order_id,user_id,product,amount,coins,consent_version,payment_key,status) VALUES('old','legacy','three',4900,3,'old','old-key','done')")
assert.equal((await request('legacy','old','legacy-request')).status,'review')
await order('o4','external','one');await value("SELECT flag_external_refund('o4','외부 취소 확인') value")
assert.equal((await reserve('external','blocked')).error,'balance')
assert.equal((await request('external','o4','external-request')).status,'review')
// Stale generation returns its original credit, and late completion cannot consume it again.
await order('o5','stale','one');const st=await reserve('stale','stale-job')
await db.query("UPDATE generation_jobs SET updated_at=now()-interval '21 minutes' WHERE id=$1",[st.id])
const newer=await reserve('stale','newer');assert.ok(newer.id);assert.equal((await finish(st,true)).error,'stale');await finish(newer,false)
assert.equal(await balance('stale'),1)
// A review quote is not an authorization to refund a balance that was spent later.
await order('o6','quote-race')
const qr=await request('quote-race','o6','quote-request','duplicate')
const quote=await value('SELECT refund_review_quote($1) value',[qr.id]);assert.equal(quote.amount,4900)
const qj=await reserve('quote-race','after-quote');await finish(qj,true)
assert.equal((await value('SELECT decide_refund($1,$2,true,$3,$4) value',[qr.id,'owner','중복 확인',quote.amount])).error,'quote_changed')
assert.equal(await balance('quote-race'),2)
const updated=await value('SELECT refund_review_quote($1) value',[qr.id]);assert.equal(updated.amount,3267)
const accepted=await value('SELECT decide_refund($1,$2,true,$3,$4) value',[qr.id,'owner','변경 금액 확인',updated.amount]);assert.equal(accepted.status,'queued')
for(const role of ['anon','authenticated']){await db.exec('SET ROLE '+role);await assert.rejects(()=>db.query('SELECT * FROM refund_requests'));await assert.rejects(()=>db.query("SELECT request_refund('buyer','o1','unused','','steal',NULL)"));await db.exec('RESET ROLE')}
console.log('PASS refund SQL: ownership; free/paid attribution; migration replay; exact partial refund; hold vs generation; 10 duplicate requests; processor lease; settlement replay; over-refund protection; content review/revocation; failed job restoration; lifetime trial; external/legacy review; stale job; RLS')
await db.close()
