import {useState} from 'react'
import Link from 'next/link'
import {NYANG_PRICE} from '@/lib/pricing'
import {trackFunnel} from './funnel'
export const guideReasons=['돈과 일의 고민에 현실적인 한마디','기질과 반복되는 선택을 이해하고 싶을 때','두 사람의 마음과 관계를 살펴보고 싶을 때','지금의 고민을 긴 흐름에서 보고 싶을 때']
const samples=[
 {id:'saju',label:'일·돈',eyebrow:'고민 예시 · 일과 선택',title:'“지금 하는 일을 계속해도 될까요?”',body:'지금 일이 힘든 이유가 일 자체인지, 일하는 조건인지 먼저 나눠보세요. 사람을 상대하는 과정은 즐겁지만 마감과 정산이 버겁다면, 직업 전체보다 역할의 배분을 살펴볼 수 있어요. 지난 일주일에서 힘이 났던 순간과 가장 지쳤던 순간을 각각 세 가지 적어보세요.',warning:'오늘의 한 걸음 · 그만둘지 결정하기 전에, 조정할 수 있는 조건 하나를 찾아보세요.'},
 {id:'strategy',label:'관계',eyebrow:'고민 예시 · 가까운 사람',title:'“좋아하는데 왜 자꾸 엇갈릴까요?”',body:'연락이 줄었을 때 관심이 식었다고 느끼는 사람과, 함께 있는 시간에 집중하는 사람이 만날 수 있어요. 같은 상황에 다른 의미를 붙이고 있는지 살펴보세요. 가장 최근에 서운했던 장면을 평가 없이 말하고, 그때 무엇을 바랐는지 한 문장으로 알려보세요.',warning:'조심할 것 · 상대의 마음을 추측한 결론과, 실제로 들은 말을 구분해보세요.'},
 {id:'question',label:'나의 기준',eyebrow:'고민 예시 · 반복되는 선택',title:'“왜 늘 비슷한 고민을 할까요?”',body:'다시 같은 고민을 한다고 해서 아무것도 달라지지 않은 것은 아니에요. 선택 직전에 어떤 조건이 반복됐는지 돌아보세요. 피곤한 시간에 급하게 답했는지, 거절하기 어려운 부탁이었는지 살펴보면 다음에 바꿔볼 지점이 구체적으로 보입니다.',warning:'오늘의 한 걸음 · 같은 상황이 오면 바로 답하기 전에 잠시 확인할 시간을 요청해보세요.'}
]
export function ResultProof(){const [current,setCurrent]=useState(0);const sample=samples[current];return <section className="sg-section cv-proof" id="result-preview" aria-labelledby="proof-title"><div className="sg-heading"><h2 id="proof-title">받게 될 이야기를<br/>먼저 읽어보세요.</h2></div><p className="cv-intro">고민에 가까운 이야기를 골라 해설과 조언의 형식을 확인해보세요.</p><div className="cv-proof-layout"><div><div className="cv-tabs" role="tablist" aria-label="고민별 해석 예시">{samples.map((s,i)=><button type="button" key={s.id} role="tab" id={'proof-tab-'+s.id} aria-selected={current===i} aria-controls="proof-panel" tabIndex={current===i?0:-1} onClick={()=>{setCurrent(i);trackFunnel('proof_tab',s.id)}} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(current+(e.key==='ArrowRight'?1:2))%3;setCurrent(n);document.getElementById('proof-tab-'+samples[n].id)?.focus()}}}>{s.label}</button>)}</div><article className={'cv-sample cv-sample-'+sample.id} id="proof-panel" role="tabpanel" aria-labelledby={'proof-tab-'+sample.id}><div className="cv-sample-meta"><span>{sample.eyebrow}</span><small>가상 예시</small></div><h3>{sample.title}</h3><p>{sample.body}</p><aside>{sample.warning}</aside></article></div><div className="cv-proof-aside"><ol><li><b>나의 사주 원국</b><span>시주·일주·월주·연주와 오행</span></li><li><b>12개의 해석 카드</b><span>기질·돈·일·관계와 주의할 점</span></li><li><b>인생 전략과 흐름</b><span>5구간 그래프와 시기별 조언</span></li><li><b>선택질문 답변</b><span>입력한 질문이 있을 때 별도 제공</span></li></ol><Link className="cv-outline" href="/?reading=saju" onClick={()=>trackFunnel('result_example_open','saju')}>전체 결과 예시 보기 ↗</Link><small>로그인 없이 확인할 수 있는 가상 결과입니다.<br/>개인의 실제 사주를 분석한 내용이 아닙니다.</small></div></div></section>}
export function ProductConditions(){return <div className="cv-conditions"><div><b>사주 풀이</b><p>해석 1회 <strong>{NYANG_PRICE.toLocaleString()}원 / 1냥</strong></p></div><div><b>일일운세</b><p>계정당 최초 1회 무료<br/>저장한 결과 재열람 무료</p></div><small>1냥 1,900원 · 3냥 4,900원. 궁합·대운·택일·연도별 운세는 계산 검증 중이며, 무료 상품으로 제공하지 않습니다.</small></div>}
export function ServiceFAQ(){return <section className="sg-section cv-faq" aria-labelledby="faq-title"><div className="sg-heading"><h2 id="faq-title">시작하기 전에</h2></div>{[
 ['일일운세와 사주 풀이는 어떻게 다른가요?','일일운세는 오늘의 총운·재물·관계·건강과 조언을 봅니다. 사주 풀이는 12개의 해석 카드와 인생 전략을 중심으로 읽고, 선택질문을 남기면 그 답변을 함께 확인합니다.'],
 ['무료 체험은 매일 받을 수 있나요?','무료 일일운세는 가입 계정당 최초 한 번입니다. 날짜나 캐릭터가 바뀌어도 무료 횟수가 다시 생기지 않습니다. 받은 결과는 다시 읽을 수 있으며, 추가 이용권은 준비 중입니다.'],
 ['태어난 시간을 몰라도 볼 수 있나요?','시간은 비워두어도 됩니다. 시주 칸은 시간 미입력으로 표시하며, 입력된 생년월일을 바탕으로 해석합니다. 모르는 시간을 임의로 넣지 마세요.'],
 ['누가 해석을 작성하나요?','사주 정보를 계산한 뒤 AI가 선택한 캐릭터의 말투로 해석을 작성합니다. 캐릭터는 가상의 안내자입니다. 사주 해석은 오락·참고용으로 이용해주세요.'],
 ['결과를 받기까지 무엇을 하나요?','캐릭터를 고르고 생년월일 정보를 입력합니다. 해석 준비 화면을 거쳐 결과를 읽습니다. 현재 비공개 샘플은 예시 결과로 이 흐름을 체험할 수 있습니다.']
 ].map(([q,a])=><details key={q} onToggle={e=>{if(e.currentTarget.open)trackFunnel('faq_open',String(['일일','무료','태어난','누가','결과'].findIndex(x=>q.startsWith(x))))}}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</section>}
export function DailyNextStep(){return <aside className="cv-daily-next"><span>오늘의 운세를 넘어</span><h2>나를 더 길게 이해하고 싶다면</h2><p>사주 풀이에서는 기질·돈·일·관계의 12개 해석과 인생 전략을 읽을 수 있어요.</p><Link href="/?reading=saju" onClick={()=>trackFunnel('daily_to_example','saju')}>사주 결과 예시 먼저 보기 →</Link><Link href="/saju" onClick={()=>trackFunnel('daily_to_saju','saju')}>내 사주 풀이 시작하기</Link></aside>}
