import {useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {trackFunnel} from './funnel'
import './journey.css'

type Saved={id:string;title:string;text:string;note:string;done:boolean;created:string;sourceHref?:string}
const sourcePaths=['/daily','/gunghap','/daeun','/taekil','/yearly',...['daily','saju','gunghap','daeun','taekil','yearly','saju-incomplete'].map(k=>'/?reading='+k)]
function safeSource(path:string|null|undefined){return path&&sourcePaths.includes(path)?path:'/?reading=saju'}
function currentSource(){const kind=new URLSearchParams(window.location.search).get('reading');return safeSource(kind?'/?reading='+kind:window.location.pathname)}
const recordKey='sajugung-local-notebook-v1'
const chatKey='sajugung-conversation-example-v1'
function records():Saved[]{try{const a=JSON.parse(localStorage.getItem(recordKey)||'[]');return Array.isArray(a)?a.filter(x=>typeof x?.id==='string'&&typeof x?.text==='string').slice(0,30):[]}catch{return []}}
function writeRecords(a:Saved[]){localStorage.setItem(recordKey,JSON.stringify(a));window.dispatchEvent(new Event('sajugung-notebook'))}
function useRecords(){const [items,setItems]=useState<Saved[]>(records);useEffect(()=>{const refresh=()=>setItems(records());window.addEventListener('sajugung-notebook',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('sajugung-notebook',refresh);window.removeEventListener('storage',refresh)}},[]);return items}
export function ReturnToReading(){const items=useRecords();if(!items.length)return null;return <aside className="jr-return"><span>내가 남긴 이야기</span><h2>{items.filter(i=>!i.done).length? '다시 읽고 싶은 조언이 있어요.':'기록한 선택을 돌아볼까요?'}</h2><p>{items[0].text.slice(0,100)}{items[0].text.length>100?'…':''}</p><Link href="/notebook">내 실천 기록 {items.length}개 보기 →</Link><small>이 브라우저에 저장한 샘플 기록</small></aside>}
export function TrustNote(){return <section className="sg-section jr-trust" aria-labelledby="jr-trust-title"><span>사주궁의 풀이 방식</span><h2 id="jr-trust-title">무엇을 바탕으로 읽어주나요?</h2><ol><li><b>01</b><div><h3>입력한 생년월일로 계산</h3><p>만세력과 오행 등 계산된 정보를 해석에 사용합니다. 모르는 출생 시간은 비워둘 수 있어요.</p></div></li><li><b>02</b><div><h3>고민과 캐릭터를 함께 반영</h3><p>AI가 선택한 캐릭터의 말투로 풀이합니다. 캐릭터는 가상의 안내자이며, 확정된 미래를 알려주는 서비스는 아닙니다.</p></div></li><li><b>03</b><div><h3>받은 결과는 다시 읽기</h3><p>사주 기본 해석 12개와 인생 전략을 확인합니다. 선택질문을 입력했다면 별도 답변이 함께 제공됩니다.</p></div></li></ol><div className="jr-trust-links"><Link href="/payments">결제·환불 내역</Link><Link href="/terms#refund">환불 기준 확인</Link></div></section>}

export function ReadingCompanion({sections,character,readingTitle}:{readingTitle:string;sections:{id:string;title:string;body?:string}[];character:string}){
 const choices=sections.filter(s=>s.body).slice(0,24)
 const [choice,setChoice]=useState(choices[0]?.id||''),[note,setNote]=useState(''),[message,setMessage]=useState(''),[share,setShare]=useState(false),[confirmed,setConfirmed]=useState(false),[shareMessage,setShareMessage]=useState('')
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null)
 const selected=choices.find(s=>s.id===choice)||choices[0]
 const excerpt=(selected?.body?.split('\n\n')[0]||'').slice(0,240)
 const id=readingTitle+':'+character+':'+(selected?.id||'')
 const saved=useRecords().some(i=>i.id===id)
 useEffect(()=>{if(share)dialog.current?.showModal();else dialog.current?.close()},[share])
 function closeShare(){setShare(false);trigger.current?.focus()}
 function save(){try{const list=records();const old=list.find(i=>i.id===id);const item={id,title:selected.title,text:excerpt,note:note||old?.note||'',done:old?.done||false,created:old?.created||new Date().toISOString(),sourceHref:currentSource()};writeRecords([item,...list.filter(i=>i.id!==id)].slice(0,30));setMessage('이 브라우저의 실천 기록에 저장했어요.');trackFunnel('advice_save','result')}catch{setMessage('저장하지 못했어요. 브라우저의 저장 공간 설정을 확인해주세요.')}}
 async function copy(){try{await navigator.clipboard.writeText('사주궁 · 해석 형식 예시\n'+selected.title+'\n\n'+excerpt);setShareMessage('미리보기에 보이는 문장만 복사했어요.');trackFunnel('share_excerpt_copy','result')}catch{setShareMessage('복사하지 못했어요. 아래 문장을 직접 선택해 복사해주세요.')}}
 if(!selected)return null
 return <section className="jr-companion" aria-labelledby="jr-title"><div className="jr-heading"><span>읽고 난 뒤의 한 걸음</span><h2 id="jr-title">내 일상에 남길 이야기</h2><p>지금 와닿는 문장을 고르고, 내가 해볼 일을 하나 적어보세요.</p></div><label className="jr-label">남겨둘 해석<select value={choice} onChange={e=>{setChoice(e.target.value);setMessage('');setShareMessage('');setConfirmed(false)}}>{choices.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><blockquote>{excerpt}</blockquote><label className="jr-label">내가 해볼 일 <span>(선택)</span><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={300} placeholder="예: 오늘 일을 마치고, 지키고 싶은 기준 두 가지 적기"/></label><div className="jr-actions"><button className="jr-primary" onClick={save}>{saved?'내 기록에 다시 저장':'내 기록에 저장하기'}</button><button ref={trigger} onClick={()=>{setShareMessage('');setConfirmed(false);setShare(true)}}>공유할 문장 확인</button></div>{message&&<p className="jr-status" role="status">{message}</p>}<div className="jr-small-row"><Link href="/notebook">저장한 조언 다시 보기 →</Link><small>개인 메모는 공유 문장에 포함되지 않아요.</small></div><Link className="jr-chat-entry" href={'/chat?guide='+encodeURIComponent(character)+'&source='+encodeURIComponent(currentSource())} onClick={()=>trackFunnel('followup_open',character)}><img src={'/characters/'+character+'.png'} alt=""/><div><span>해석 뒤에 남은 질문</span><b>캐릭터에게 이어서 물어보기</b><small>자유롭게 이어 묻기 · 첫 답변 1회 무료</small></div><span aria-hidden="true">↗</span></Link><p className="jr-local-note">기록은 이 브라우저에만 저장됩니다. 실제 계정 보관함과 연결되는 기능은 운영 반영 전 검증합니다.</p><dialog className="jr-share-dialog" ref={dialog} onCancel={closeShare} aria-labelledby="jr-share-title"><button className="jr-dialog-close" onClick={closeShare} aria-label="공유 미리보기 닫기">×</button><h2 id="jr-share-title">공유할 문장 미리보기</h2><p>아래 카드에 보이는 제목과 문장만 복사합니다.</p><article className="jr-share-card"><span>사주궁 · 해석 형식 예시</span><h3>{selected.title}</h3><p>{excerpt}</p><footer>나를 돌아보는 한 문장 · 四柱宮</footer></article><label className="jr-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>이 문장에 공유하고 싶지 않은 개인정보나 고민이 없는지 확인했어요.</span></label><button className="jr-primary" disabled={!confirmed} onClick={copy}>이 문장만 복사하기</button>{shareMessage&&<p className="jr-status" role="status">{shareMessage}</p>}<small>비공개 시안에서는 외부 게시나 카카오 전송이 발생하지 않습니다.</small></dialog></section>
}

function RecordItem({item,onChange,onDelete}:{item:Saved;onChange:(i:Saved)=>boolean;onDelete:()=>void}){const [note,setNote]=useState(item.note),[message,setMessage]=useState('');return <article className="jr-record"><span>{item.done?'돌아본 기록':'내가 해볼 일'}</span><h2>{item.title}</h2><blockquote>{item.text}</blockquote><label className="jr-label">내 메모<textarea value={note} onChange={e=>{setNote(e.target.value);setMessage('')}} maxLength={300}/></label><div className="jr-actions"><button onClick={()=>{setMessage(onChange({...item,note})?'메모를 저장했어요.':'메모를 저장하지 못했어요.')}}>메모 저장</button><button aria-pressed={item.done} onClick={()=>onChange({...item,done:!item.done,note})}>{item.done?'다시 실천할 일로':'돌아봤어요 ✓'}</button></div>{message&&<p role="status">{message}</p>}<Link className="jr-end-link" href={safeSource(item.sourceHref)}>이 조언의 결과 다시 보기 →</Link><button className="jr-delete" onClick={onDelete}>이 기록 삭제</button></article>}
export function NotebookPage(){const items=useRecords(),[message,setMessage]=useState(''),[undo,setUndo]=useState<Saved|null>(null);function change(item:Saved){try{writeRecords(records().map(i=>i.id===item.id?item:i));setMessage('');return true}catch{setMessage('기록을 저장하지 못했어요.');return false}}function remove(item:Saved){try{writeRecords(records().filter(i=>i.id!==item.id));setUndo(item);setMessage('기록을 삭제했어요.')}catch{setMessage('삭제하지 못했어요.')}}return <main className="jr-page"><header><Link href="/">← 사주궁</Link><span>나의 실천 기록</span></header><p className="jr-eyebrow">읽었던 이야기, 그다음의 나</p><h1>내가 남긴 한 걸음</h1><p>기억해두고 싶은 조언과 내가 해본 일을 함께 돌아보세요.</p><p className="jr-local-note">이 브라우저에만 저장되는 샘플입니다. 브라우저 데이터를 삭제하면 기록도 사라집니다.</p>{message&&<p className="jr-status" role="status">{message}</p>}{undo&&<button onClick={()=>{try{writeRecords([undo,...records().filter(i=>i.id!==undo.id)]);setUndo(null);setMessage('기록을 복원했어요.')}catch{setMessage('복원하지 못했어요.')}}}>삭제 되돌리기</button>}{items.length?<><p className="jr-count">저장 {items.length}개 · 돌아본 기록 {items.filter(i=>i.done).length}개</p>{items.map(i=><RecordItem key={i.id} item={i} onChange={change} onDelete={()=>remove(i)}/>)}</>:<section className="jr-empty"><h2>아직 남긴 기록이 없어요.</h2><p>결과 예시에서 마음에 남는 해석을 하나 골라보세요.</p><Link href="/?reading=saju">사주 결과에서 기록해보기 →</Link></section>}<Link className="jr-end-link" href="/?reading=saju">사주 결과 예시 보기 →</Link></main>}

export function resetConversation(){}
